import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import ReduxProvider from "@app/app/storeProvider";
import { Suspense } from 'react'
import { NavigationEvents } from "@app/components/Managers/PQCOnavigationManager";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//TODO add a custom 404 page
//TODO add react redux

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          <Suspense fallback={null}>
              <NavigationEvents />
          </Suspense>
          </body>
      </html>
    </ReduxProvider>
  );
}
